version: 0.2
phases:
  install:
    commands:
      - apt update 
      - apt install docker -y
      - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
  pre_build:
    commands:
      - echo DB_PASSWORD=2YsaTLxtzQzorB6rq2Qmpr@3mLsRGN29 >> .env
      - echo c453f4e1291100fb53e9408819b9c4509f1d6961 >> ~/tok.txt
      - cat ~/tok.txt | docker login https://docker.pkg.github.com -u arturolc --password-stdin
  build:  
    commands:
      - docker-compose up
  post_build:
    commands:
      - echo "No test to run"