version: 0.2
env:
  secrets-manager:
     github_key: GITHUB_TOKEN
     db_pw: DB_PASSWORD
phases:
  install:
    commands:
      - apt update 
      - apt install docker -y
      - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
  pre_build:
    commands:
      - echo DB_PASSWORD=$db_password >> .env
      - echo $github_key | docker login https://docker.pkg.github.com -u arturolc --password-stdin
  build:  
    commands:
      - docker-compose up
  post_build:
    commands:
      - echo "No test to run"
